services:
  postgres:
    image: postgres:17.5-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - cesizen
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    

  next:
    build:
      context: .
      target: next
    container_name: next
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
    restart: always
    volumes:
      - .:/app

    networks:
      - cesizen
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  pgdata:

networks:
  cesizen:
    driver: bridge
